"""0001_init

Revision ID: c72c5d7c6c05
Revises:
Create Date: 2026-09-02 21:35:55.239470

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c72c5d7c6c05"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conflict",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("entity", sa.String(), nullable=True),
        sa.Column("row_id", sa.String(), nullable=True),
        sa.Column("device_id", sa.String(), nullable=True),
        sa.Column("base_rev", sa.Integer(), nullable=True),
        sa.Column("server_row", sa.String(), nullable=True),
        sa.Column("local_row", sa.String(), nullable=True),
        sa.Column("winner", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("resolved_at", sa.String(), nullable=True),
        sa.Column("resolution", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "device",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("platform", sa.String(), nullable=True),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("last_seen_at", sa.String(), nullable=True),
        sa.Column("revoked_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="uq_device_token"),
    )
    op.create_table(
        "media",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("rev", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("deleted_at", sa.String(), nullable=True),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.Column("mime", sa.String(), nullable=False),
        sa.Column("ext", sa.String(), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("uploaded", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256", name="uq_media_sha"),
    )
    with op.batch_alter_table("media", schema=None) as batch_op:
        batch_op.create_index("idx_media_rev", ["rev"], unique=False)

    op.create_table(
        "meta",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "op_log",
        sa.Column("client_op_id", sa.String(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=True),
        sa.Column("entity", sa.String(), nullable=True),
        sa.Column("row_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("applied_rev", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("client_op_id"),
    )
    op.create_table(
        "pairing",
        sa.Column("code_hash", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("expires_at", sa.String(), nullable=True),
        sa.Column("used_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("code_hash"),
    )
    op.create_table(
        "reminder_log",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("todo_id", sa.String(), nullable=True),
        sa.Column("fire_at", sa.String(), nullable=True),
        sa.Column("fingerprint", sa.String(), nullable=False),
        sa.Column("channel", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("detail", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint", name="uq_reminder_fp"),
    )
    op.create_table(
        "seq",
        sa.Column("k", sa.Integer(), nullable=False),
        sa.Column("v", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("k"),
        sa.UniqueConstraint("k", name="uq_seq_k"),
    )
    op.create_table(
        "setting",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("rev", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("deleted_at", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", name="uq_setting_key"),
    )
    with op.batch_alter_table("setting", schema=None) as batch_op:
        batch_op.create_index("idx_setting_rev", ["rev"], unique=False)

    op.create_table(
        "term",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("rev", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("deleted_at", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("start_date", sa.String(), nullable=False),
        sa.Column("weeks_total", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("term", schema=None) as batch_op:
        batch_op.create_index("idx_term_rev", ["rev"], unique=False)

    op.create_table(
        "attachment",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("rev", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("deleted_at", sa.String(), nullable=True),
        sa.Column("media_id", sa.String(), nullable=False),
        sa.Column("owner_type", sa.String(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("caption", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("attachment", schema=None) as batch_op:
        batch_op.create_index("idx_attachment_rev", ["rev"], unique=False)

    op.create_table(
        "course",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("rev", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("deleted_at", sa.String(), nullable=True),
        sa.Column("term_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("short_name", sa.String(), nullable=True),
        sa.Column("teacher", sa.String(), nullable=True),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("color", sa.Integer(), nullable=False),
        sa.Column("credit", sa.Float(), nullable=True),
        sa.Column("exam_at", sa.String(), nullable=True),
        sa.Column("exam_room", sa.String(), nullable=True),
        sa.Column("exam_note", sa.String(), nullable=True),
        sa.Column("textbook", sa.String(), nullable=True),
        sa.Column("grade_breakdown", sa.String(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["term.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("course", schema=None) as batch_op:
        batch_op.create_index("idx_course_rev", ["rev"], unique=False)

    op.create_table(
        "lesson_period",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("rev", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("deleted_at", sa.String(), nullable=True),
        sa.Column("term_id", sa.String(), nullable=False),
        sa.Column("lesson_no", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.String(), nullable=False),
        sa.Column("end_time", sa.String(), nullable=False),
        sa.Column("big_period", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["term.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lesson_period", schema=None) as batch_op:
        batch_op.create_index("idx_lesson_period_rev", ["rev"], unique=False)

    op.create_table(
        "timetable_override",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("rev", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("deleted_at", sa.String(), nullable=True),
        sa.Column("term_id", sa.String(), nullable=False),
        sa.Column("day", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("course_id", sa.String(), nullable=True),
        sa.Column("slot_id", sa.String(), nullable=True),
        sa.Column("to_weekday", sa.Integer(), nullable=True),
        sa.Column("to_start_lesson", sa.Integer(), nullable=True),
        sa.Column("to_end_lesson", sa.Integer(), nullable=True),
        sa.Column("room", sa.String(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["term.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("timetable_override", schema=None) as batch_op:
        batch_op.create_index("idx_timetable_override_rev", ["rev"], unique=False)

    op.create_table(
        "course_slot",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("rev", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("deleted_at", sa.String(), nullable=True),
        sa.Column("course_id", sa.String(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("start_lesson", sa.Integer(), nullable=False),
        sa.Column("end_lesson", sa.Integer(), nullable=False),
        sa.Column("room", sa.String(), nullable=True),
        sa.Column("weeks", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("course_slot", schema=None) as batch_op:
        batch_op.create_index("idx_course_slot_rev", ["rev"], unique=False)

    op.create_table(
        "todo",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("rev", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("deleted_at", sa.String(), nullable=True),
        sa.Column("course_id", sa.String(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("body_text", sa.String(), nullable=False),
        sa.Column("due_at", sa.String(), nullable=True),
        sa.Column("start_at", sa.String(), nullable=True),
        sa.Column("due_all_day", sa.Integer(), nullable=False),
        sa.Column("repeat", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("done_at", sa.String(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("tags", sa.String(), nullable=False),
        sa.Column("remind_mode", sa.String(), nullable=False),
        sa.Column("remind_offsets", sa.String(), nullable=True),
        sa.Column("sort_order", sa.Float(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("todo", schema=None) as batch_op:
        batch_op.create_index("idx_todo_rev", ["rev"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todo", schema=None) as batch_op:
        batch_op.drop_index("idx_todo_rev")

    op.drop_table("todo")
    with op.batch_alter_table("course_slot", schema=None) as batch_op:
        batch_op.drop_index("idx_course_slot_rev")

    op.drop_table("course_slot")
    with op.batch_alter_table("timetable_override", schema=None) as batch_op:
        batch_op.drop_index("idx_timetable_override_rev")

    op.drop_table("timetable_override")
    with op.batch_alter_table("lesson_period", schema=None) as batch_op:
        batch_op.drop_index("idx_lesson_period_rev")

    op.drop_table("lesson_period")
    with op.batch_alter_table("course", schema=None) as batch_op:
        batch_op.drop_index("idx_course_rev")

    op.drop_table("course")
    with op.batch_alter_table("attachment", schema=None) as batch_op:
        batch_op.drop_index("idx_attachment_rev")

    op.drop_table("attachment")
    with op.batch_alter_table("term", schema=None) as batch_op:
        batch_op.drop_index("idx_term_rev")

    op.drop_table("term")
    with op.batch_alter_table("setting", schema=None) as batch_op:
        batch_op.drop_index("idx_setting_rev")

    op.drop_table("setting")
    op.drop_table("seq")
    op.drop_table("reminder_log")
    op.drop_table("pairing")
    op.drop_table("op_log")
    op.drop_table("meta")
    with op.batch_alter_table("media", schema=None) as batch_op:
        batch_op.drop_index("idx_media_rev")

    op.drop_table("media")
    op.drop_table("device")
    op.drop_table("conflict")
    # ### end Alembic commands ###
