import { appendFileSync, existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { execFileSync } from 'node:child_process'

const mobileRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const androidRoot = join(mobileRoot, 'android')
const npx = process.platform === 'win32' ? 'npx.cmd' : 'npx'
const appVersion = JSON.parse(readFileSync(join(mobileRoot, 'package.json'), 'utf8')).version

if (!existsSync(androidRoot)) {
  execFileSync(npx, ['cap', 'add', 'android'], { cwd: mobileRoot, stdio: 'inherit' })
}

const propertiesPath = join(androidRoot, 'gradle.properties')
const marker = 'android.overridePathCheck=true'
const properties = existsSync(propertiesPath) ? readFileSync(propertiesPath, 'utf8') : ''
if (!properties.includes(marker)) {
  appendFileSync(propertiesPath, `\n${marker}\n`)
}

const gradlePath = join(androidRoot, 'app', 'build.gradle')
if (existsSync(gradlePath)) {
  const gradle = readFileSync(gradlePath, 'utf8')
  const nextGradle = gradle.replace(/versionName "[^"]+"/, `versionName "${appVersion}"`)
  if (nextGradle !== gradle) writeFileSync(gradlePath, nextGradle)
}

const manifestPath = join(androidRoot, 'app', 'src', 'main', 'AndroidManifest.xml')
if (existsSync(manifestPath)) {
  const manifest = readFileSync(manifestPath, 'utf8')
  const permission = '    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />'
  if (!manifest.includes('android.permission.REQUEST_INSTALL_PACKAGES')) {
    writeFileSync(manifestPath, manifest.replace('</manifest>', `${permission}\n</manifest>`))
  }
}

writeFileSync(join(androidRoot, '.supercourse-ready'), 'generated by prepare-android.mjs\n')
