import { appendFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { execFileSync } from 'node:child_process'

import { makePng } from '../../web/scripts/gen-icons.mjs'

const mobileRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const androidRoot = join(mobileRoot, 'android')
const npx = process.platform === 'win32' ? 'npx.cmd' : 'npx'
const appVersion = JSON.parse(readFileSync(join(mobileRoot, 'package.json'), 'utf8')).version
const versionCode = appVersion
  .split('.')
  .map(Number)
  .reduce((value, part, index) => value + part * [10000, 100, 1][index], 0)

if (!existsSync(androidRoot)) {
  execFileSync(npx, ['cap', 'add', 'android'], { cwd: mobileRoot, stdio: 'inherit' })
}

const propertiesPath = join(androidRoot, 'gradle.properties')
const marker = 'android.overridePathCheck=true'
const properties = existsSync(propertiesPath) ? readFileSync(propertiesPath, 'utf8') : ''
if (!properties.includes(marker)) {
  appendFileSync(propertiesPath, `\n${marker}\n`)
}

const gradlePath = join(androidRoot, 'app', 'build.gradle')
if (existsSync(gradlePath)) {
  const gradle = readFileSync(gradlePath, 'utf8')
  const nextGradle = gradle
    .replace(/versionCode \d+/, `versionCode ${versionCode}`)
    .replace(/versionName "[^"]+"/, `versionName "${appVersion}"`)
  if (nextGradle !== gradle) writeFileSync(gradlePath, nextGradle)
}

const manifestPath = join(androidRoot, 'app', 'src', 'main', 'AndroidManifest.xml')
if (existsSync(manifestPath)) {
  const manifest = readFileSync(manifestPath, 'utf8')
  const permission = '    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />'
  if (!manifest.includes('android.permission.REQUEST_INSTALL_PACKAGES')) {
    writeFileSync(manifestPath, manifest.replace('</manifest>', `${permission}\n</manifest>`))
  }
}

// Android 启动图标与 Web/Desktop 共用同一份品牌图形，避免 Capacitor 初始图标回退成旧菱形。
const iconSizes = { ldpi: 36, mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192 }
const resRoot = join(androidRoot, 'app', 'src', 'main', 'res')
for (const [density, size] of Object.entries(iconSizes)) {
  const iconDir = join(resRoot, `mipmap-${density}`)
  mkdirSync(iconDir, { recursive: true })
  const png = makePng(size, 0.18)
  writeFileSync(join(iconDir, 'ic_launcher.png'), png)
  writeFileSync(join(iconDir, 'ic_launcher_round.png'), png)
}
writeFileSync(join(mobileRoot, 'resources', 'icon.png'), makePng(512, 0.18))

// 保留完整方形品牌图标，移除 Capacitor 默认的 v26 自适应菱形资源，确保新旧 Android 都显示同一图形。
const adaptiveIconDir = join(resRoot, 'mipmap-anydpi-v26')
rmSync(join(adaptiveIconDir, 'ic_launcher.xml'), { force: true })
rmSync(join(adaptiveIconDir, 'ic_launcher_round.xml'), { force: true })

writeFileSync(join(androidRoot, '.supercourse-ready'), 'generated by prepare-android.mjs\n')
